#ifndef FLV_PUB_HPP
#define FLV_PUB_HPP

#define FLV_TAG_AUDIO 0x08
#define FLV_TAG_VIDEO 0x09

#define FLV_VIDEO_KEY_FLAG   1
#define FLV_VIDEO_INTER_FLAG 2

#define FLV_VIDEO_AVC_SEQHDR 0
#define FLV_VIDEO_AVC_NALU   1

#define FLV_VIDEO_H264_CODEC 0x07
#define FLV_VIDEO_H265_CODEC 0x0c

#define FLV_AUDIO_AAC_CODEC  0x0a

#endif